### ISSUE TITLE
Should not include trailing slashes when sending URI prefix / instance URL

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/Web-of-Registries#20]
Should not have trailing slashes.  These should either be trimmed before being sent to WoR or trimmed upon receipt.

**Comment by 3ach** [comment]
Okay, this is more clear. This should be on this side. I will clear it off the SBH issue tracker.

**Comment by cjmyers** [comment]
Well, it should be SBH I think, since what it sends to register should not have trailing slashes.

**Comment by 3ach** [comment]
You can do it either place, but I would prefer to do it here because SynBioHub is not the only way to send WoR join requests, you can also do it through the API. Makes more sense to enforce the invariant on this end.

**Comment by cjmyers** [comment]
I think WoR should actually throw an error if the format is incorrect for the URL.  SBH should always make a proper request.

**Comment by 3ach** [comment]
But that's not an incorrect URL, it's a quirk with SynBioHub, right?
