### ISSUE TITLE
200 given even on bad requests

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/Web-of-Registries#21]
Error messages are returned in the body, so they are not detected upon receipt.  One example is if the administrator email is missing.

**Comment by cjmyers** [comment]
Another example is when a denial or deletion happens.  This needs to return an error and cause SynBioHub to delete its Web of Registries secret, etc.

**Comment by 3ach** [comment]
Errors coming back in the body of the request is correct, but the request code should also reflect an error

**Comment by 3ach** [comment]
Wait, actually, I get a 400 on bad requests. Are you getting something different @cjmyers ?

**Comment by cjmyers** [comment]
Seems I was getting through then crashing, needed a catch to send back a better error page.

**Comment by 3ach** [comment]
Was this on the Web of Registries or on SynBioHub?

Thanks,
Zach

**Comment by cjmyers** [comment]
Received on sbh but sent by wor

Chris

**Comment by 3ach** [comment]
Can you provide the steps for reproduction? Was it a crash of SBH or WoR?

Thanks,
Zach

**Comment by cjmyers** [comment]
Try making a request to join WoR without an administrator email.

**Comment by 3ach** [comment]
I get a 400 response with this body:
```json
{
    "name": "SequelizeValidationError",
    "errors": [
        {
            "message": "administratorEmail cannot be null",
            "type": "notNull Violation",
            "path": "administratorEmail",
            "value": null
        }
    ]
}
```

I think this is correct, the error messages will be displayed on the SBH registry admin page.
