### ISSUE TITLE
Web of registries does not work for local instances

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/Web-of-Registries#22]
You cannot register to the web of registries a server that cannot be found.  For example, if you register localhost, it will not be able to communicate with it.   Therefore, WoR should confirm that it can reach the SynBioHub instance, basically do an are you alive call, perhaps using the rootCollections endpoint to see if a response comes.  In the future, other tests may be in order to tests its API.  Only if these work, should it accept the request, otherwise should send a denial immediately.

**Comment by 3ach** [comment]
What about displaying an indicator on a registry's card on the Web of Registries showing whether or not the last request to that registry worked? I don't know about sending an immediate denial; but I think it is useful information for the approver.

**Comment by cjmyers** [comment]
It would be nice if a local instance could fetch the web of registries without registering itself.  

As for registering, a local instance should not be allowed to even try to register, since it cannot work.  Not sure how you can detect that you are not public facing though.

**Comment by 3ach** [comment]
Fetching-without-registering is already an open SBH issue! :smile: 
I think that we agreed in the call today that this should just be the 'currently accessible' icon in the WoR and in the SBH admin, which both have open issues, so I'm closing this.
