### ISSUE TITLE
Deny request for any registry with URI prefix matching already approved registry

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/Web-of-Registries#24]
There can only be one registry for each URI prefix, so any request that has the same URI prefix as an approved registry should be denied.

**Comment by 3ach** [comment]
Should the same be true of instance URLs?

**Comment by 3ach** [comment]
It's done for uriPrefix, if you want it for instanceUrl as well, please open a separate issue.

**Comment by cjmyers** [comment]
Key is with URI prefix.  Guess possible to have multiple prefixes for a single repo, so perhaps it is ok.
